version: '3.9'

services:
  postgres:
    image: postgis/postgis:12-3.0-alpine
    restart: unless-stopped
    volumes:
      - oe_pg_dc_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: open_event_user
      POSTGRES_PASSWORD: opev_pass
      POSTGRES_DB: oevent

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    command: redis-server
    volumes:
      - oe_redis_dc_data:/var/lib/redis/data

  open-event-server:
    build: .
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    ports:
      - 5000:8080
    environment:
      - DATABASE_URL=postgresql://open_event_user:opev_pass@postgres:5432/oevent
      - SECRET_KEY=741a6f7389de40a91b930869b5e32baaae6953170b6fc1b9856001598a5ef0b8 # random generate using secrets
      - REDIS_URL=redis://redis:6379/0
      - SUPER_ADMIN_EMAIL=open_event_test_user@fossasia.org
      - SUPER_ADMIN_PASSWORD=fossasia
      - INTEGRATE_SOCKETIO=false
      - APP_CONFIG=config.DevelopmentConfig
      - FLASK_APP=app.instance
    command: waitress-serve app.instance:current_app

  celery:
    build: .
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://open_event_user:opev_pass@postgres:5432/oevent
      - SECRET_KEY=741a6f7389de40a91b930869b5e32baaae6953170b6fc1b9856001598a5ef0b8 # random generate using secrets
      - REDIS_URL=redis://redis:6379/0
      - SUPER_ADMIN_EMAIL=open_event_test_user@fossasia.org
      - SUPER_ADMIN_PASSWORD=fossasia
      - INTEGRATE_SOCKETIO=false
      - APP_CONFIG=config.DevelopmentConfig
      - FLASK_APP=app.instance
    command: celery -A app.instance.celery worker -B -l INFO -c 2

  oes-init-db:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://open_event_user:opev_pass@postgres:5432/oevent
      - SECRET_KEY=741a6f7389de40a91b930869b5e32baaae6953170b6fc1b9856001598a5ef0b8 # random generate using secrets
      - REDIS_URL=redis://redis:6379/0
      - SUPER_ADMIN_EMAIL=open_event_test_user@fossasia.org
      - SUPER_ADMIN_PASSWORD=fossasia
      - INTEGRATE_SOCKETIO=false
      - APP_CONFIG=config.DevelopmentConfig
      - FLASK_APP=app.instance
    command: python manage.py prepare_db

volumes:
  oe_pg_dc_data:
  oe_redis_dc_data:
